version: '3.8'

# 개발 서버용 docker compose
services:
  nestjs:
    build: .
    image: manito42/dev
    container_name: manito42_dev
    depends_on:
      - mysql
    ports:
      - "80:3000"
    networks:
      - backend
    working_dir: /app
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul

  mysql:
    image: mysql:8.0.33
    container_name: mysql_dev
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: manito
      MYSQL_USER: manito
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge