# Dependency Install, Build, Start를 여기서 다합니다.
name: Production Deploy to AWS
on:
  pull_request:
    branches:
      - test_deploy # master, develop 브랜치로 변경되어야함.
env:
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    permissions:
      id-token: write
      contents: write

    name: Build Application
    runs-on: ubuntu-22.04
    steps:
      # 레포지토리로 이동합니다.
      - name: Checkout
        uses: actions/checkout@v3
      # npm cache
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}.
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: build
        run: npm run build